
export const REQUEST_NEWS_LIST =            'GET_NEWS_LIST_REQUEST';
export const REQUEST_NEWS_LIST_SUCCESS =    'GET_NEWS_LIST_SUCCESS';
export const REQUEST_NEWS_LIST_FAIL =       'GET_NEWS_LIST_FAIL';

export const REQUEST_NEWS_DETAILS =         'GET_NEWS_DETAILS_REQUEST';
export const REQUEST_NEWS_DETAILS_SUCCESS = 'GET_NEWS_DETAILS_SUCCESS';
export const REQUEST_NEWS_DETAILS_FAIL =    'GET_NEWS_DETAILS_FAIL';

